### ISSUE TITLE
Input `sequence` not in Unicode error

### ISSUE THREAD

**Issue by yarinkel** [Neftas/supplementary-buttons-anki#53]
Getting this error with the 10 December 2015 release.
Anki Version 2.0.33
Qt 4.8.2 PyQt 4.9.4
OSX 10.11.2
I tried to delete and reinstall the plug-in but I get the same error

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/addons.pyc", line 41, in loadAddons
  File "/Users/yann/Documents/Anki/addons/Supplementary Buttons Anki.py", line 2, in <module>
  File "/Users/yann/Documents/Anki/addons/extra_buttons/extra_buttons.py", line 558, in <module>
  File "/Users/yann/Documents/Anki/addons/extra_buttons/preferences.py", line 159, in __init__
  File "/Users/yann/Documents/Anki/addons/extra_buttons/utility.py", line 658, in check_user_keybindings
  File "/Users/yann/Documents/Anki/addons/extra_buttons/utility.py", line 577, in validate_key_sequence
AssertionError: Input `sequence` not in Unicode

**Comment by Neftas** [comment]
Hi @yarinkel, thanks for reporting this.

I couldn't really reproduce the error you have, but have made sure that all the handling of key sequences is now guaranteed to be Unicode. You can update the addon on Ankiweb.

(Did you by any change put non-Latin characters in your key-bindings file? That would probably explain the exception you got.)

**Comment by yarinkel** [comment]
Hi @Neftas,
thanks for taking care so quickly of this. With the new version, the error has changed to:

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/addons.pyc", line 41, in loadAddons
  File "/Users/yann/Documents/Anki/addons/Supplementary Buttons Anki.py", line 2, in <module>
  File "/Users/yann/Documents/Anki/addons/extra_buttons/extra_buttons.py", line 558, in <module>
  File "/Users/yann/Documents/Anki/addons/extra_buttons/preferences.py", line 125, in __init__
NameError: global name 'codec' is not defined

**Comment by Neftas** [comment]
Okay, I tried to solve that too quickly. Thanks for providing additional details. I have uploaded a revised version to Ankiweb. If this does not solve the problem, I will take a closer look at it tomorrow. It may have something to do with a Mac. If the new version works, I would be glad if you could report back here.

**Comment by yarinkel** [comment]
I just changed the line in the file preferences.py 
from
`with codec.open(self.prefs_path, "w", encoding="utf8") as f:`
to
`with codecs.open(self.prefs_path, "w", encoding="utf8") as f:`

and it's working now. Thanks a lot!

**Comment by yarinkel** [comment]
Oh, we crossed path! :)
Anyway, I deleted the plugin with that modification I made and reinstalled your latest version (as from 22:16 CET time.)
I'm glad to report it's working fine now!

Thanks a lot!

**Comment by Neftas** [comment]
Awesome! I indeed made a typo, I'm ashamed to admit. But am I glad it works now, and a big thank you to you for reporting this and making this addon better for everybody. If you find something else, please keep reporting it!

**Comment by yarinkel** [comment]
My pleasure! It's me who owe you a big thank for making this awesome plugin. I use it almost daily and would not even dream of formatting numerous dictionary definitions without it!
