### ISSUE TITLE
Error Opening Add Card Dialog

### ISSUE THREAD

**Issue by QuixoticBuddha** [Neftas/supplementary-buttons-anki#58]
This is the error text.
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.webview", line 18, in run
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.editor", line 481, in bridge
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.hooks", line 26, in runHook
  File "C:\Users\User\Documents\Anki\addons\extra_buttons\extra_buttons.py", line 510, in on_focus_gained
    html_field, field, u"")
  File "C:\Users\User\Documents\Anki\addons\extra_buttons\markdowner.py", line 40, in __init__
    assert isinstance(html, unicode), "Input `html` is not Unicode"
AssertionError: Input `html` is not Unicode

**Comment by Neftas** [comment]
Thanks for reporting.

Could you be a little more specific on what you were trying to do? The stack trace doesn't give much information. What was the text you were entering? Was it empty by any chance?

**Comment by Neftas** [comment]
I just uploaded version 0.8.3 to Anki. Could you check if this fixes your problem?
