### ISSUE TITLE
Error after  installing Power Format Pack

### ISSUE THREAD

**Issue by uitalo** [Neftas/supplementary-buttons-anki#61]
Hi, 

Hi, after I installed this plug in, 
I got the following error when I re-opened anki:
"Um erro ocorreu em um complemento.
Por favor, publique isto no fórum do complemento:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\anki\build\anki2\out00-PYZ.pyz\aqt.addons", line 41, in loadAddons
  File "C:\Users\cassio\Documents\Anki\addons\Supplementary Buttons Anki.py", line 2, in <module>
    import extra_buttons.extra_buttons
  File "C:\Users\cassio\Documents\Anki\addons\extra_buttons\extra_buttons.py", line 41, in <module>
    from anki_modules.aqt import editor as myeditor
  File "C:\Users\cassio\Documents\Anki\addons\extra_buttons\anki_modules\aqt\editor.py", line 11, in <module>
    from utility import Utility
  File "C:\Users\cassio\Documents\Anki\addons\extra_buttons\utility.py", line 35, in <module>
    import markdown
  File "C:\Users\cassio\Documents\Anki\addons\extra_buttons\markdown\__init__.py", line 40, in <module>
    from ..python_modules import importlib
ValueError: Attempted relative import beyond toplevel package"

I use Windows 10 in PC. This error started to happen after the implementation of Markdown.

**Comment by Neftas** [comment]
Hi @uitalo, thanks for reporting.

I have uploaded a new version to AnkiWeb. Could you reinstall the addon (remove the folder from <User>/Documents/Anki/addons as well just to be safe) and report if it works now? Thanks!

**Comment by uitalo** [comment]
still does not work:Um erro ocorreu em um complemento.
Por favor, publique isto no fórum do complemento:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\anki\build\anki2\out00-PYZ.pyz\aqt.addons", line 41, in loadAddons
  File "C:\Users\cassio\Documents\Anki\addons\Supplementary Buttons Anki.py", line 2, in <module>
    import extra_buttons.extra_buttons
  File "C:\Users\cassio\Documents\Anki\addons\extra_buttons\extra_buttons.py", line 41, in <module>
    from anki_modules.aqt import editor as myeditor
  File "C:\Users\cassio\Documents\Anki\addons\extra_buttons\anki_modules\aqt\editor.py", line 11, in <module>
    from utility import Utility
  File "C:\Users\cassio\Documents\Anki\addons\extra_buttons\utility.py", line 35, in <module>
    import markdown
  File "C:\Users\cassio\Documents\Anki\addons\extra_buttons\markdown\__init__.py", line 44, in <module>
    from .treeprocessors import build_treeprocessors
  File "C:\Users\cassio\Documents\Anki\addons\extra_buttons\markdown\treeprocessors.py", line 5, in <module>
    from . import inlinepatterns
  File "C:\Users\cassio\Documents\Anki\addons\extra_buttons\markdown\inlinepatterns.py", line 50, in <module>
    from ..urllib import parse
ValueError: Attempted relative import beyond toplevel package

**Comment by Neftas** [comment]
This is a strange error. I have checked the addon on Windows 7, Windows 8.1 and Windows 10, and I do not get the error you are getting. Seeing the path you are launching Anki from, I suspect that you got a custom installation of Anki somewhere not from the Anki site? I would recommend you reinstall Anki and use only the default installation provided by the [official Anki website](http://ankisrs.net/). Please let me know if that resolves the issue.

**Comment by uitalo** [comment]
Well, my solution was to move the Anki folder in My Documents and reinstall the plugin, then worked. I think there should be a conflict between plugins.

**Comment by Neftas** [comment]
Great. Still, to ensure the proper working of all add-ons, I would recommend using the default paths. Anyway, I am glad you got it working. Closing this.
