### ISSUE TITLE
Error on startup: ImportError: cannot import name bytes

### ISSUE THREAD

**Issue by jaabio** [Neftas/supplementary-buttons-anki#68]
Hi,

I installed the latest version of the addon.  But now when I start Anki I get the following error.  Any suggestions about how to fix it?  Thanks much.

    Traceback (most recent call last):
      File "aqt/addons.pyc", line 41, in loadAddons
      File "/Users/****/Documents/Anki/addons/Syntax Highlighting for Code.py", line 2, in <module>
      File "/Users/****/Documents/Anki/addons/code_highlight_addon/code_highlight_addon.py", line 201, in <module>
      File "/Users/****/Documents/Anki/addons/code_highlight_addon/pygments/lexers/__init__.py", line 19, in <module>
    ImportError: cannot import name bytes

**Comment by jaabio** [comment]
This error started happening after I installed the latest version of Supplementary Buttons.  But I just realized it's originating from another plugin - Syntax Highlighting for Code.  I don't use that plugin much, so I uninstalled it.  Now no more error.

**Comment by Neftas** [comment]
@jaabio What's even better, you don't need Syntax Highlighting for Code anymore, because Supplementary Buttons for Anki provides the same functionality. Just "fence" your code block like this:

    ```c
    int main(int argc, char *argv[]) {
        puts("Awesome highlighting all alround!");
    }
    ```
hit the Markdown button and it will display like

```c
int main(int argc, char *argv[]) {
    puts("Awesome highlighting all alround!");
}
```

**Comment by jaabio** [comment]
@Neftas Yup! Thanks. And thanks for an awesome plugin!
