### ISSUE TITLE
crash on start in windows

### ISSUE THREAD

**Issue by gunnarmaluf** [Neftas/supplementary-buttons-anki#69]
I get this message when I try to open anki after installing:
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.addons", line 41, in loadAddons
  File "c:\pyi\iu.py", line 436, in importHook
  File "c:\pyi\iu.py", line 521, in doimport
  File "D:\N�o Apagar\Documents\Anki\addons\Supplementary Buttons Anki.py", line 2, in <module>
    import extra_buttons.extra_buttons
  File "c:\pyi\iu.py", line 436, in importHook
  File "c:\pyi\iu.py", line 521, in doimport
  File "D:\N�o Apagar\Documents\Anki\addons\extra_buttons\extra_buttons.py", line 33, in <module>
    import utility
  File "c:\pyi\iu.py", line 436, in importHook
  File "c:\pyi\iu.py", line 521, in doimport
  File "D:\N�o Apagar\Documents\Anki\addons\extra_buttons\utility.py", line 42, in <module>
    from markdown.extensions.codehilite import CodeHiliteExtension
  File "c:\pyi\iu.py", line 436, in importHook
  File "c:\pyi\iu.py", line 521, in doimport
  File "D:\N�o Apagar\Documents\Anki\addons\extra_buttons\markdown\extensions\codehilite.py", line 36, in <module>
    package = unicode(package, "utf8")
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/encodings.utf_8", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 4: invalid continuation byte

**Comment by Neftas** [comment]
Looks like the same problem as #60.
