### ISSUE TITLE
Add-on error dialog when editing note

### ISSUE THREAD

**Issue by jaabio** [Neftas/supplementary-buttons-anki#73]
Hi,
I keep getting the following error dialog, even after updating to latest version of the add-on.
It showed when the Edit Current dialog was opened to edit an existing note containing plain text and cloze deletions only, no markup or lists or anything else.
I'm on Mac El Capitan 10.11.3
Anki Version 2.0.33
Thanks.
Julian

```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/webview.pyc", line 18, in run
  File "aqt/editor.pyc", line 481, in bridge
  File "anki/hooks.pyc", line 26, in runHook
  File "/Users/jdoe/Documents/Anki/addons/extra_buttons/extra_buttons.py", line 597, in on_focus_gained
    self.saveNow()
  File "aqt/editor.pyc", line 562, in saveNow
  File "aqt/editor.pyc", line 658, in saveTags
  File "anki/notes.pyc", line 47, in flush
AssertionError
```

**Comment by Neftas** [comment]
Thanks for taking the time to report this. I have tried to reproduce this on a MacBook with the same versions you mentioned, but I cannot seem to get the same error as you get. So can you be a little bit more specific about when this error message appears?

You can always try to reinstall Anki and this addon and see if that helps.

**Comment by jaabio** [comment]
Thanks for looking int the issue.  I'll try reinstalling both the app and addon and report back.

**Comment by Neftas** [comment]
Closing this for no activity over 6 months.
