### ISSUE TITLE
Error occurred in the add-on

### ISSUE THREAD

**Issue by vpopmachine** [Neftas/supplementary-buttons-anki#91]
Traceback (most recent call last):
  File "aqt/addons.pyc", line 41, in loadAddons
  File "/Users/Pandapants/Documents/Anki/addons/Supplementary Buttons Anki.py", line 2, in <module>
  File "/Users/Pandapants/Documents/Anki/addons/power_format_pack/extra_buttons.py", line 32, in <module>
  File "/Users/Pandapants/Documents/Anki/addons/power_format_pack/utility.py", line 42, in <module>
  File "/Users/Pandapants/Documents/Anki/addons/power_format_pack/markdown/__init__.py", line 44, in <module>
  File "/Users/Pandapants/Documents/Anki/addons/power_format_pack/markdown/treeprocessors.py", line 5, in <module>
  File "/Users/Pandapants/Documents/Anki/addons/power_format_pack/markdown/inlinepatterns.py", line 50, in <module>
ValueError: Attempted relative import beyond toplevel package

**Comment by Neftas** [comment]
@vpopmachine Thanks for reporting this.

In your stacktrace, I noticed the old add-on filename being mentioned. Could you do the following:

1. Remove the add-on from Anki (_Tools_ > _Add-ons..._ > _Power Format Pack_ > _Delete..._).
2. Remove the add-on from disk: go to _\<Documents\>/Anki/addons_ and remove all files related to _Power Format Pack_.
3. Reinstall the add-on.

Does that resolve the issue?

**Comment by vpopmachine** [comment]
Unfortunately I did not. I received the following message:

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):

File "aqt/addons.pyc", line 41, in loadAddons

File "/Users/Pandapants/Documents/Anki/addons/Supplementary Buttons
Anki.py", line 2, in <module>

File
"/Users/Pandapants/Documents/Anki/addons/power_format_pack/extra_buttons.py",
line 32, in <module>

File
"/Users/Pandapants/Documents/Anki/addons/power_format_pack/utility.py",
line 42, in <module>

File
"/Users/Pandapants/Documents/Anki/addons/power_format_pack/markdown/__init__.py",
line 44, in <module>

File
"/Users/Pandapants/Documents/Anki/addons/power_format_pack/markdown/treeprocessors.py",
line 5, in <module>

File
"/Users/Pandapants/Documents/Anki/addons/power_format_pack/markdown/inlinepatterns.py",
line 50, in <module>

ValueError: Attempted relative import beyond toplevel package

**Comment by vpopmachine** [comment]
I just removed the Supplementary Buttons Anki add-on and re-installed Power
Format Pack. It worked.
