### ISSUE TITLE
Power Format Pack breaks with Anki version 2.1.x

### ISSUE THREAD

**Issue by ghost** [Neftas/supplementary-buttons-anki#96]
# Error:
```
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 47, in loadAddons
    __import__(file.replace(".py", ""))
  File "/home/ackbar/Documents/Anki/addons21/Power Format Pack.py", line 2, in <module>
    import power_format_pack.extra_buttons
  File "/home/ackbar/Documents/Anki/addons21/power_format_pack/__init__.py", line 1, in <module>
    from docs._version import __version__
ModuleNotFoundError: No module named 'docs'
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 52, in loadAddons
    __import__(directory)
  File "/home/ackbar/Documents/Anki/addons21/power_format_pack/__init__.py", line 1, in <module>
    from docs._version import __version__
ModuleNotFoundError: No module named 'docs'
```
# Anki Information

Version 2.1.0a10
Qt 5.8.0 PyQt 5.8

# System Information

OS: Arch Linux x86-64
HW: Thinkpad T440S
Kernel: 4.9.9-1-ARCH

**Comment by Neftas** [comment]
### Short answer

You need to downgrade Anki from the **alpha 2.1.x** to the stable **2.0.x** branch.

### Background

You are currently using an alpha build of Anki. Apparently, Anki 2.1 migrates away from Python 2 and PyQt4 towards Python 3 and PyQt5. Python 3 is **not** backwards compatible with Python 2 and therefore most Anki add-ons will break with the alpha version.

Arch, for some reason, packaged the alpha version. See also [this announcement from the Anki team about this issue](https://anki.tenderapp.com/kb/anki-ecosystem/arch-linux-has-packaged-an-alpha-build-that-could-cause-data-loss).

**Comment by zog34** [comment]
It looks like Anki has been pulled from the pacman repository because of [security issues with qtwebkit](https://www.archlinux.org/todo/phasing-out-qtwebkit/). This will continue to be a problem until Anki utilizes a more up-to-date package. I'm going to mark this as closed because it is an upstream problem.

**Comment by CarlosEvo** [comment]
Any progress on Anki 2.1 support? Its been out for quite a while... I am looking forward to it...

**Comment by lukaskawerau** [comment]
Yes, is there any progress? Anki 2.1 has now been in Beta for a while, would be great if there would be an update soon :)

**Comment by Neftas** [comment]
@CarlosEvo @lukaskawerau there is currently no work being done to make this
add-on compatible with Anki 2.1. In theory, it should not be too difficult,
but I currently don't have any time to work on it.

Also, I feel that the code could use a major update from what it is right now.
I've been working on this add-on from when I just learned to code, and there
are a lot of areas that I feel could use improvement to make it more
maintainable. There are some hacks and workarounds that seemed reasonable at
the time that should also be taken care of.

Although I'm sorry to disappoint you guys, I feel that if I would work on
porting this to 2.1, I should deliver something to the best of my current
ability, and not hack something together that would "work" on 2.1 but that
people would complain about.

If someone is willing to put in the time and effort, I would be glad to offer
assistance wherever I can. But to honest, and as many people have pointed out,
some of the functionality of this add-on would be better as part of core Anki
itself. So another option would be to make pull requests to upstream and
include some of the functionality this add-on provides.

**Comment by mattepiu** [comment]
2to3 script will do the most of the work, changing code wherever it can and marking where it cannot.
https://docs.python.org/3/library/2to3.html

**Comment by Neftas** [comment]
@mattepiu Thanks, I did something similar some time ago, but the dependencies that are included with Power Format Pack should also be updated to Python 3. Just running the 2to3 script will be a poor solution to upgrading those dependencies. (The 2to3 script leaves a lot of broken code. That means that I have to dive into why the code is broken, leading me to read articles about what changed in Python 3, debug sessions, and a lot of time invested. So, it's a good first step, but all the hard work has to come after that.)

**Comment by glutanimate** [comment]
Having ported quite a few add-ons now, I can confirm what Stefan said: Although scripts like 2to3 or pyqt4topyqt5 really do help, there still is a lot of manual work involved in porting an add-on as complex as PFP to 2.1.

If anyone is interested in tackling this, I've recently released a highly cut-down version of PFP called [Mini Format Pack](https://github.com/glutanimate/mini-format-pack/) ([AnkiWeb link](https://ankiweb.net/shared/info/295889520)). Although it's very far from a proper port, I hope that it can at least serve as an example on how some things like adding buttons to the editor etc. now work on 2.1.

I would like to explore adding more features to the add-on in the future, but I'm not sure at the moment when I'll find the time for that.
